### PR TITLE
Docs: Add script for generating game image repository readme content and generated game image repository readme files

### PR DESCRIPTION
**Pull request by joeltimothyoh**
The script that I've been using all along for generating individual game image repository readme content.

### CODE REVIEW

**Comment by joeltimothyoh** [comment]
We'll do that in a separate PR.

**Comment by leojonathanoh** [comment]
i dont see a need to generate the separate `.md` files for each image. so we can just use this PR to do exactly https://github.com/startersclan/docker-sourceservers/pull/28#issuecomment-954936857

**Comment by joeltimothyoh** [comment]
It's for the `README.md` for each image repo like https://hub.docker.com/r/sourceservers/csgo @leojonathanoh

**Comment by leojonathanoh** [comment]
oic, ok then but it does look a bit confusing. perhpas the path could be `/docs/dockerhub/srcds/csgo/README.md`. Or, use a github action to populate docker hub readme.

**Comment by joeltimothyoh** [comment]
> oic, ok then but it does look a bit confusing. perhpas the path could be /docs/dockerhub/srcds/csgo/README.md. Or, use a github action to populate docker hub readme.

I'm not aware of there being an API for updating docker hub repository `README.md` content.

**Comment by leojonathanoh** [comment]
- https://github.com/marketplace/actions/docker-hub-description
- https://github.com/marketplace/actions/docker-hub-readme-description-sync
- 
second one might be better

**Comment by joeltimothyoh** [comment]
We don't use GHA in this repository.

**Comment by leojonathanoh** [comment]
if thats the case you have to manually udpate each docker hub repo. And this PR makes the source of truth the generator `.ps1` script, so this repo may use github ci to populate the repo description and readme.

**Comment by joeltimothyoh** [comment]
We'll think of adding support so in another PR. This one lgtm

**Pull request merged**
