### PR TITLE
Docs: Update CircleCI build badges links for CircleCI new UI update

### PR DESCRIPTION
**Pull request by joeltimothyoh**
Addresses #13

### CODE REVIEW

**Comment by joeltimothyoh** [comment]
One thing though. As of the new UI update, it doesn’t look like build logs are publicly viewable without a sign-in to CircleCI. @leojonathanoh

**Comment by leojonathanoh** [comment]
> One thing though. As of the new UI update, it doesn’t look like build logs are publicly viewable without a sign-in to CircleCI. @leojonathanoh

strange. Maybe it’s something to do with marking the repo public or private

**Comment by joeltimothyoh** [comment]
> strange. Maybe it’s something to do with marking the repo public or private

Shouldn't that also depend on the visibility of the GitHub project itself? There's only one setting under **Project Setting** > **Advanced** > **Free and Open Source** which if enabled sets the CI build limits for the project under the CircleCI's OSS plan.

I don't think it's difficult to figure the reasons for the changes.

**Comment by leojonathanoh** [comment]
yes, circleci determines ci repo’s visibility based on the visibility of the github repo. I checked and there is no setting on the new UI to control visibility of the ci repo. So it’s that, whether it’s deliberate or not is out of the picture but it is not hard to figure.

**Comment by joeltimothyoh** [comment]
The old UI hasn't yet been disabled. We'll just hold out from merging until need be since jobs are at least publicly viewable without a sign-in to CircleCI. @leojonathanoh

**Comment by joeltimothyoh** [comment]
The old UI seems to have been removed. Think we can merge this in. @leojonathanoh

**Pull request merged**
